### PR TITLE
Support arrays of array

### PR DESCRIPTION
**Pull request by histausse**
Add test for #313 and implement a fix.

### CODE REVIEW

**Comment by histausse** [comment]
(I did not manage to get frida to use a different version of the bridge, so the only tests I did are the one run by `make check`)

**Comment by nezza** [comment]
I tested this patch and can confirm it fixes issues with nested arrays. Thanks a lot!


@histausse to use a different version I followed the instructions here: https://github.com/frida/frida-tools/blob/main/README.md#loading-your-custom-frida-java-bridge
As long as your frida-version is compatible with the frida-tools tag you checked out it should work well :)

**Comment by histausse** [comment]
> I tested this patch and can confirm it fixes issues with nested arrays. Thanks a lot!
> 
> @histausse For me the instructions here worked well: https://github.com/frida/frida-tools/blob/main/README.md#loading-your-custom-frida-java-bridge As long as your frida-version is compatible with the frida-tools tag you checked out it should work well. Which issue did you run into?

The bridge used is just not the modified one. Here os how a tried to add an "hello world" in `Java.use`:

```
$ git clone https://github.com/frida/frida-tools.git
$ cd frida-tools/
$ git checkout 12.3.0
$ python -m venv venv
$ source venv/bin/activate
$ export PYTHONPATH=$(pwd)
$ echo $PYTHONPATH
/tmp/tmp.9HAJacCmdN/frida-tools
$ cd agents/tracer/
$ npm link frida-java-bridge
$ # edit agents/tracer/agent.ts and agents/tracer/node_modules/frida-java-bridge/index.js and run npm link frida-java-bridge in another term
$ cd -
$ head -n 3 agents/tracer/agent.ts
Object.defineProperty(global, 'Java', { value: require('frida-java-bridge') });;

class Agent {
$ grep -A 2 -B 2 Hello agents/tracer/node_modules/frida-java-bridge/index.js

  use (className, options) {
    console.log("Hello World!");
    return this.classFactory.use(className, options);
  }
$ pip install .
$ frida -U TestClassLoader
     ____
    / _  |   Frida 16.2.1 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Android Emulator 5554 (id=emulator-5554)

[Android Emulator 5554::TestClassLoader ]-> Java.use("java.lang.Class")
"<class: java.lang.Class>"
[Android Emulator 5554::TestClassLoader ]->
```
I'm verry unfamilliar with javascript dependencies management (and javascript in general) so it's probably on me, do you see any obvious mistake in my process?

**Comment by nezza** [comment]
Hmmm I did pretty much the same, only difference is that I have the modification in agent.ts on the bottom of the file - have you checked whether your PYTHONPATH is respected? I.e. is the correct frida-tools loaded? Do you see npm watch doing something when you modify the file? (Not a JS dependency expert at all either.)

**Comment by oleavr** [comment]
Whoa, nice! 💥 Thanks for doing this, and apologies for the delay -- just finished a painful restructuring of the build system and reviving CI across the Frida project.

I've pushed some style adjustments and minor simplifications, but haven't gotten a chance to test them yet. It's a bank holiday today so I might not get around to it until tomorrow. But if any of you are able to take it for a spin in the meantime, please do let me know. (I'll try to take a stab at reviving the frida-java-bridge CI soon.)

**Pull request merged**
