### PR TITLE
add Java.deoptimizeMethod to call art::Dbg::RequestDeoptimization

### PR DESCRIPTION
**Pull request by liuyufei**
add Java.deoptimizeMethod to call art::Dbg::RequestDeoptimization with selectiveDeoptimizaion option to deoptimize specific method.

This PR can provide frida to deoptimize specific method for the situation that specific method hooking is not taken effect. This will reduce the overhead for turn on all the deoptimizations and keep the app's running performance.

### CODE REVIEW

**Comment by oleavr** [comment]
Thanks, this is great! Did you intend to close this PR?

**Comment by liuyufei** [comment]
We can reopen the PR, but in some cases Java.deoptimizeMethod will crash the app. I need more testing to find the crash reason and confirm this PR run normally.

This is the crash log. It will be great if you could help to analysis the reason. 

```
01-29 15:04:26.862 25723 25737 F stack.cc:883] Check failed: GetMethod() == callee (GetMethod()=0x7098c041f0, callee=0x70140a10) Expected: <runtime method>.<runtime internal callee-save reference and argument registers method> Found: boolean java.lang.String.equals(java.lang.Object)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] Runtime aborting --- recursively, so no thread-specific detail!
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #00 pc 00000000003c7324  /system/lib64/libart.so (offset 257000) (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+220)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #01 pc 000000000046a980  /system/lib64/libart.so (offset 257000) (art::Runtime::Abort(char const*)+312)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #02 pc 0000000000008d2c  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+724)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #03 pc 0000000000484e3c  /system/lib64/libart.so (offset 257000) (_ZN3art12StackVisitor9WalkStackILNS0_16CountTransitionsE0EEEvb+3756)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #04 pc 0000000000499df8  /system/lib64/libart.so (offset 257000) (art::Thread::DumpJavaStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, bool) const+320)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #05 pc 0000000000495dd8  /system/lib64/libart.so (offset 257000) (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+376)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #06 pc 00000000004afd5c  /system/lib64/libart.so (offset 257000) (art::DumpCheckpoint::Run(art::Thread*)+844)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #07 pc 00000000004a8a9c  /system/lib64/libart.so (offset 257000) (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+476)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #08 pc 00000000004a7cd4  /system/lib64/libart.so (offset 257000) (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool)+500)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #09 pc 000000000046a9d0  /system/lib64/libart.so (offset 257000) (art::Runtime::Abort(char const*)+392)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #10 pc 0000000000008d2c  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+724)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #11 pc 0000000000484e3c  /system/lib64/libart.so (offset 257000) (_ZN3art12StackVisitor9WalkStackILNS0_16CountTransitionsE0EEEvb+3756)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #12 pc 00000000004891b4  /system/lib64/libart.so (offset 257000) (art::StackVisitor::ComputeNumFrames(art::Thread*, art::StackVisitor::StackWalkKind)+84)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #13 pc 000000000024d554  /system/lib64/libart.so (offset aa000) (art::instrumentation::Instrumentation::PushInstrumentationStackFrame(art::Thread*, art::mirror::Object*, art::ArtMethod*, unsigned long, bool)+476)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #14 pc 000000000051ec54  /system/lib64/libart.so (offset 257000) (artInstrumentationMethodEntryFromCode+1044)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #15 pc 0000000000565e60  /system/lib64/libart.so (offset 53e000) (art_quick_instrumentation_entry+96)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #16 pc 000000000055cb88  /system/lib64/libart.so (offset 50e000) (art_quick_invoke_stub+584)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #17 pc 00000000000cf740  /system/lib64/libart.so (offset a8000) (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #18 pc 00000000004633b8  /system/lib64/libart.so (offset 257000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #19 pc 0000000000463010  /system/lib64/libart.so (offset 257000) (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+416)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #20 pc 0000000000346258  /system/lib64/libart.so (offset 257000) (art::JNI::CallNonvirtualBooleanMethodV(_JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list)+648)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #21 pc 00000000000fffe8  /system/lib64/libart.so (offset aa000) (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primitive::Type, art::InvokeType)+1576)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #22 pc 00000000000ed85c  /system/lib64/libart.so (offset aa000) (art::(anonymous namespace)::CheckJNI::CallNonvirtualBooleanMethod(_JNIEnv*, _jobject*, _jclass*, _jmethodID*, ...)+156)
01-29 15:04:26.875 25723 25737 F runtime.cc:558] #23 pc 00000000001ea324  /data/local/tmp/frida-7ac52a70553d81d86a9cb528a4160f07/frida-agent-64.so (???)
01-29 15:04:26.875 25723 25737 F runtime.cc:558]
01-29 15:04:26.878 25723 25737 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 25737 (Binder:25723_3), pid 25723
```

**Comment by oleavr** [comment]
(Apologies for the delay here, got distracted for a while!)

> in some cases Java.deoptimizeMethod will crash the app

Aha, I see. We could merge this even if it sometimes crashes – we can get to the bottom of that later.

Only two issues remaining to merge:
1. Should refine the API a bit. It would be good to pass in the Java method instead of specifying `className, methodName, description`.
2. Most of the logic is the same as in `deoptimizeEverything()` – this should be refactored to avoid duplicating everything.

**Comment by liuyufei** [comment]
> 1. Should refine the API a bit. It would be good to pass in the Java method instead of specifying className, methodName, description.
> 2. Most of the logic is the same as in deoptimizeEverything() – this should be refactored to avoid duplicating logic.

Hi oleavr, I have solved these two issues.

**Comment by oleavr** [comment]
Thanks! (And apologies for the delay here! 😓)

**Pull request merged**
