### PR TITLE
Make _ZNK3art6Thread13DecodeJObjectEP8_jobject optional

### PR DESCRIPTION
**Pull request by gsingh93**
This will fix https://github.com/frida/frida/issues/2468

### CODE REVIEW

**Comment by gsingh93** [comment]
As this is only used for Android 6 and lower, I think making it optional makes sense instead of having a fallback.

And as a sidenote, I think the current system of looking for these methods is prone to break often. I would suggest instead of attempting to find every method not marked as optional, we just find the version of android we're connecting to, and then have a list of APIs that were added/removed from each version. Then, if we have an API in the "removed" list for Android 7, it will still be required for Android 6 and lower, but not required for anything above Android 6.

**Comment by gsingh93** [comment]
@oleavr can you run the checks that require approval?

**Comment by AAGaming00** [comment]
Might be slightly off-topic, but how would I build a frida-server binary that uses this?

**Comment by gsingh93** [comment]
The build instructions are the normal ones for Frida, except to use the local version of frida-java-bridge I had to make this modification to frida-gum: https://github.com/gsingh93/frida-gum/commit/dabfe43ecbeb1a83a02b4628e8f85c723accc206

I've asked in #288 what the right way to use a local version of a library is.

**Pull request merged**
