### PR TITLE
Fixed for Issue #136

### PR DESCRIPTION
**Pull request by gebing**

### CODE REVIEW

**Comment by gebing** [comment]
I prefer to make a method to explicitly get an extra handle/wrapper.

**Comment by gebing** [comment]
Actually there is no need for a new method, just use Java.cast() which can explicitly get an extra handle/wrapper.

**Comment by oleavr** [comment]
Agreed. I also thought of that, but I think `Java.cast()` sounds counter-intuitive. I think we want a function with a descriptive name; even if all it does is call `Java.cast()`. Some ideas:
- `Java.dup()`
- `Java.ref()`
- `Java.steal()` (this one would prevent the `.dispose()` from happening, which is probably a bit too clunky to implement)
- `.$ref()`
...

Food for thought, let's merge this in the meantime. :-)

**Comment by gebing** [comment]
From my personal opinion, I prefer to use `Java.dup()` or `Java.ref()`.

**Comment by oleavr** [comment]
Sounds good. Another idea is `Java.retain()`; what do you think?

**Comment by gebing** [comment]
`Java.retain()` sounds more good.

**Pull request merged**
